/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/trident.glb -o TridentComponent.jsx 
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trident-603aa96860c148ba996f3937cd7463ec
Title: Trident
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/trident.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.handle_handle_0.geometry} material={materials.handle} position={[70.654, 158.511, -0.213]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.661, 6.661, 51.408]} />
      <mesh geometry={nodes.Plane_handle_0.geometry} material={materials.handle} position={[74.191, 389.499, 0.083]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={66.611} />
    </group>
  )
}

useGLTF.preload('/trident.glb')
